### ISSUE TITLE
Stop tracking other peoples' code

### ISSUE THREAD

**Issue by spratt** [SteamedPears/Code-Review#57]
Most of the code in the repo is library code on the client-side.  We should really use something so we stop tracking other peoples' code.

**Comment by cdelahousse** [comment]
Agreed! I've been learning about them here.

http://git-scm.com/book/en/Git-Tools-Submodules

They sound swell.

**Comment by psimonyi** [comment]
I don't like tracking other people's code, but git modules seem less than ideal. There seem to be a lot of pitfalls, and it seems to be intended for submodules maintained by the same people that own the main repo, rather than for using releases of other people's code. If there's no better way, then let's go for it, but if there's an alternative that still avoids tracking others' code, I'd like to hear it.

**Comment by spratt** [comment]
We discussed this and determined the proper course of action is to pull down and build the projects we need in the install scripts.

**Comment by spratt** [comment]
So I would like to have our install script pull down the sources for jQuery, CodeMirror, URI.js, require.js, and any other libraries we end up using on the client-side.  Does anyone know of a nice system for doing this?  Or should I roll a basic package manager using wget?  @cdelahousse @bheesham @psimonyi

**Comment by cdelahousse** [comment]
Look into Yeoman, or more specifically, Bower (http://twitter.github.com/bower/). It's supposed to be a package manager for web apps.

If not, why not just do a series of git clones?

**Comment by spratt** [comment]
In the cases of CodeMirror and URI.js, git cloning would work.  But we don't use the result of simply cloning the jquery and require.js repositories, we use some kind of built product.

**Comment by psimonyi** [comment]
Since this should all be handled by a script, we don't need a nice package-manager interface -- all that package management would get us is dependency resolution (not really useful) and automatic building (potentially useful). So if you can find a package manager that will do building stuff automatically, let's try it; otherwise, wget is probably less work and less code. In the case of jQuery, it's just one file to download.

**Comment by spratt** [comment]
The package manager also gives us that if the URL changes, it's the package manager's responsibility to know about it, we don't have to update our scripts.

**Comment by psimonyi** [comment]
In the case of bower, it seems you give it URLs except for the really popular stuff, so that's probably not really an advantage for bower. But yes, if there's a package manager that does what we need, let's use it.
