### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by bheesham** [SteamedPears/Code-Review#68]
I see in `packages.json`` we've licensed the software under the ISC License? 
Is this going to be open source?

Also, if any of the libraries that we use are GPL, what does that mean for our source?

**Comment by psimonyi** [comment]
Oh, man. GPL with interpreted code is not pretty.

**Comment by spratt** [comment]
GPL sucks.  ISC is what the front end has been since Alexis started working on it.  When we merged the repos, we decided to make the back end also ISC licensed.

We should check if we have any GPL code.  If so, we should ditch the GPL code so we're not violating the GPL.

**Comment by psimonyi** [comment]
The problem with the GPL is that it's written in terms of compiled code and static linking. As I recall, the FSF claims that dynamically linking GPL code requires everything to be GPL, which seems to be a generally accepted view, and also that interpreted languages calling stuff is basically the same as dynamic linking. Thus, the FSF wants any code that uses GPL-covered code to be GPL. It's not entirely clear that this is actually required by the license, which is why GPL for interpreted code is not nice. Also, not everyone who uses the GPL actually understands the terms they're asking people to follow. It's one of the more complicated licenses to read.

**Comment by psimonyi** [comment]
GPLv3 might have cleared this up; I haven't actually read it.

**Comment by bheesham** [comment]
```
formidable: MIT
http-proxy: MIT
node-uuid: MIT
sqlite3: BSD (3 clause)
node-static: BSD (2 clause)
sequelize: BSD (2 clause)
```

**Comment by cdelahousse** [comment]
What have we decided about this? What should be placing up top of my code? ISC?

**Comment by psimonyi** [comment]
How about this:

```
Copyright by Steamed Pears, 2013.
For licensing information, see the file LICENCE in the root directory of this project.
```

**Comment by cdelahousse** [comment]
I like that. Simple, minimalist and we won't need to modify it if our license changes.

**Comment by spratt** [comment]
That looks good.

**Comment by psimonyi** [comment]
Is this resolved? I think it is...

**Comment by psimonyi** [comment]
Conclusions:
- We're using ISC.
- New files should add a licence header; I've added it to the style guide.
- We can definitely use libraries that use ISC/BSD/MIT/Apache kinds of licences. We can't use GPL libraries, and we aren't.
- We are currently using several libraries with BSD and MIT licences, listed by Bhee above.
